tag @s remove teleporter_lobby
tag @s remove teleporter_stone
tag @s remove teleporter_andesite
tag @s remove teleporter_endstone
tag @s remove teleporter_obsidian
tag @s remove teleporter_stoneslab
tag @s remove teleporter_sandstone
tag @s remove teleporter_diorite
tag @s remove teleporter_enderore
tag @s remove teleporter_glowingobsidian
tag @s remove teleporter_netherrack
tag @s remove teleporter_nethergold
tag @s remove teleporter_soulsand
tag @s remove teleporter_hardstone