execute @a[scores={levelup_count=..-1,level=100}] ~~~ scoreboard players set @s levelup_count 0
execute @a[scores={levelup_count=..0,level=99}] ~~~ function level/lv100
execute @a[scores={levelup_count=..0,level=98}] ~~~ function level/lv99
execute @a[scores={levelup_count=..0,level=97}] ~~~ function level/lv98
execute @a[scores={levelup_count=..0,level=96}] ~~~ function level/lv97
execute @a[scores={levelup_count=..0,level=95}] ~~~ function level/lv96
execute @a[scores={levelup_count=..0,level=94}] ~~~ function level/lv95
execute @a[scores={levelup_count=..0,level=93}] ~~~ function level/lv94
execute @a[scores={levelup_count=..0,level=92}] ~~~ function level/lv93
execute @a[scores={levelup_count=..0,level=91}] ~~~ function level/lv92
execute @a[scores={levelup_count=..0,level=90}] ~~~ function level/lv91
execute @a[scores={levelup_count=..0,level=89}] ~~~ function level/lv90
execute @a[scores={levelup_count=..0,level=88}] ~~~ function level/lv89
execute @a[scores={levelup_count=..0,level=87}] ~~~ function level/lv88
execute @a[scores={levelup_count=..0,level=86}] ~~~ function level/lv87
execute @a[scores={levelup_count=..0,level=85}] ~~~ function level/lv86
execute @a[scores={levelup_count=..0,level=84}] ~~~ function level/lv85
execute @a[scores={levelup_count=..0,level=83}] ~~~ function level/lv84
execute @a[scores={levelup_count=..0,level=82}] ~~~ function level/lv83
execute @a[scores={levelup_count=..0,level=81}] ~~~ function level/lv82
execute @a[scores={levelup_count=..0,level=80}] ~~~ function level/lv81
execute @a[scores={levelup_count=..0,level=79}] ~~~ function level/lv80
execute @a[scores={levelup_count=..0,level=78}] ~~~ function level/lv79
execute @a[scores={levelup_count=..0,level=77}] ~~~ function level/lv78
execute @a[scores={levelup_count=..0,level=76}] ~~~ function level/lv77
execute @a[scores={levelup_count=..0,level=75}] ~~~ function level/lv76
execute @a[scores={levelup_count=..0,level=74}] ~~~ function level/lv75
execute @a[scores={levelup_count=..0,level=73}] ~~~ function level/lv74
execute @a[scores={levelup_count=..0,level=72}] ~~~ function level/lv73
execute @a[scores={levelup_count=..0,level=71}] ~~~ function level/lv72
execute @a[scores={levelup_count=..0,level=70}] ~~~ function level/lv71
execute @a[scores={levelup_count=..0,level=69}] ~~~ function level/lv70
execute @a[scores={levelup_count=..0,level=68}] ~~~ function level/lv69
execute @a[scores={levelup_count=..0,level=67}] ~~~ function level/lv68
execute @a[scores={levelup_count=..0,level=66}] ~~~ function level/lv67
execute @a[scores={levelup_count=..0,level=65}] ~~~ function level/lv66
execute @a[scores={levelup_count=..0,level=64}] ~~~ function level/lv65
execute @a[scores={levelup_count=..0,level=63}] ~~~ function level/lv64
execute @a[scores={levelup_count=..0,level=62}] ~~~ function level/lv63
execute @a[scores={levelup_count=..0,level=61}] ~~~ function level/lv62
execute @a[scores={levelup_count=..0,level=60}] ~~~ function level/lv61
execute @a[scores={levelup_count=..0,level=59}] ~~~ function level/lv60
execute @a[scores={levelup_count=..0,level=58}] ~~~ function level/lv59
execute @a[scores={levelup_count=..0,level=57}] ~~~ function level/lv58
execute @a[scores={levelup_count=..0,level=56}] ~~~ function level/lv57
execute @a[scores={levelup_count=..0,level=55}] ~~~ function level/lv56
execute @a[scores={levelup_count=..0,level=54}] ~~~ function level/lv55
execute @a[scores={levelup_count=..0,level=53}] ~~~ function level/lv54
execute @a[scores={levelup_count=..0,level=52}] ~~~ function level/lv53
execute @a[scores={levelup_count=..0,level=51}] ~~~ function level/lv52
execute @a[scores={levelup_count=..0,level=50}] ~~~ function level/lv51
execute @a[scores={levelup_count=..0,level=49}] ~~~ function level/lv50
execute @a[scores={levelup_count=..0,level=48}] ~~~ function level/lv49
execute @a[scores={levelup_count=..0,level=47}] ~~~ function level/lv48
execute @a[scores={levelup_count=..0,level=46}] ~~~ function level/lv47
execute @a[scores={levelup_count=..0,level=45}] ~~~ function level/lv46
execute @a[scores={levelup_count=..0,level=44}] ~~~ function level/lv45
execute @a[scores={levelup_count=..0,level=43}] ~~~ function level/lv44
execute @a[scores={levelup_count=..0,level=42}] ~~~ function level/lv43
execute @a[scores={levelup_count=..0,level=41}] ~~~ function level/lv42
execute @a[scores={levelup_count=..0,level=40}] ~~~ function level/lv41
execute @a[scores={levelup_count=..0,level=39}] ~~~ function level/lv40
execute @a[scores={levelup_count=..0,level=38}] ~~~ function level/lv39
execute @a[scores={levelup_count=..0,level=37}] ~~~ function level/lv38
execute @a[scores={levelup_count=..0,level=36}] ~~~ function level/lv37
execute @a[scores={levelup_count=..0,level=35}] ~~~ function level/lv36
execute @a[scores={levelup_count=..0,level=34}] ~~~ function level/lv35
execute @a[scores={levelup_count=..0,level=33}] ~~~ function level/lv34
execute @a[scores={levelup_count=..0,level=32}] ~~~ function level/lv33
execute @a[scores={levelup_count=..0,level=31}] ~~~ function level/lv32
execute @a[scores={levelup_count=..0,level=30}] ~~~ function level/lv31
execute @a[scores={levelup_count=..0,level=29}] ~~~ function level/lv30
execute @a[scores={levelup_count=..0,level=28}] ~~~ function level/lv29
execute @a[scores={levelup_count=..0,level=27}] ~~~ function level/lv28
execute @a[scores={levelup_count=..0,level=26}] ~~~ function level/lv27
execute @a[scores={levelup_count=..0,level=25}] ~~~ function level/lv26
execute @a[scores={levelup_count=..0,level=24}] ~~~ function level/lv25
execute @a[scores={levelup_count=..0,level=23}] ~~~ function level/lv24
execute @a[scores={levelup_count=..0,level=22}] ~~~ function level/lv23
execute @a[scores={levelup_count=..0,level=21}] ~~~ function level/lv22
execute @a[scores={levelup_count=..0,level=20}] ~~~ function level/lv21
execute @a[scores={levelup_count=..0,level=19}] ~~~ function level/lv20
execute @a[scores={levelup_count=..0,level=18}] ~~~ function level/lv19
execute @a[scores={levelup_count=..0,level=17}] ~~~ function level/lv18
execute @a[scores={levelup_count=..0,level=16}] ~~~ function level/lv17
execute @a[scores={levelup_count=..0,level=15}] ~~~ function level/lv16
execute @a[scores={levelup_count=..0,level=14}] ~~~ function level/lv15
execute @a[scores={levelup_count=..0,level=13}] ~~~ function level/lv14
execute @a[scores={levelup_count=..0,level=12}] ~~~ function level/lv13
execute @a[scores={levelup_count=..0,level=11}] ~~~ function level/lv12
execute @a[scores={levelup_count=..0,level=10}] ~~~ function level/lv11
execute @a[scores={levelup_count=..0,level=9}] ~~~ function level/lv10
execute @a[scores={levelup_count=..0,level=8}] ~~~ function level/lv9
execute @a[scores={levelup_count=..0,level=7}] ~~~ function level/lv8
execute @a[scores={levelup_count=..0,level=6}] ~~~ function level/lv7
execute @a[scores={levelup_count=..0,level=5}] ~~~ function level/lv6
execute @a[scores={levelup_count=..0,level=4}] ~~~ function level/lv5
execute @a[scores={levelup_count=..0,level=3}] ~~~ function level/lv4
execute @a[scores={levelup_count=..0,level=2}] ~~~ function level/lv3
execute @a[scores={levelup_count=..0,level=1}] ~~~ function level/lv2